### ISSUE TITLE
Show duplicate count instead of tab count

### ISSUE THREAD

**Issue by ghost** [rob-slezak/TabFind#1]
1. Would it be possible to add a feature to show duplicate count (>0) instead of tab count as the badge?  The number of tabs doesn't really tell me anything interesting.
2. Once I have duplicates then it would nice if the was a quick way (button?) to delete all but the old tab of duplicates.  Can you bind a double click on the icon?  Failing that what about double click on the "Dups" title?  The straight forward UX would be a regular button on Dups view.
3. It would be nice if the add-on remembers which of the 3 views you were on last (All, Dups or Search).  It currently always opens up on All.   You could eliminate the All view, btw, as the search gives the same information just with row less due to the search bar.

**Comment by rob-slezak** [comment]
I've made changes based on your feedback:

1) There is now an option to change the badge number to count duplicates instead of all tabs. https://github.com/rob-slezak/TabFind/commit/e0665f590bb01014d2aea4ce2023b980ad759d3e
![image](https://github.com/rob-slezak/TabFind/assets/55259013/01ab556f-9b0f-441e-9a06-154cf32413c6)

2) Added a Clear Duplicates button to the duplicates view which will remove all duplicate copies of tabs except the most recent. https://github.com/rob-slezak/TabFind/commit/9baea4078d5b343ed2718b1b776d901921dbd329
![image](https://github.com/rob-slezak/TabFind/assets/55259013/09e95f73-d0d7-42e0-9a4a-ff6e00837296)

3) Addon will now remember the previously opened view and will open to what you were on last. Also, I agree with you that All and Search were very similar so I removed the search view and added the search bar to the All view. https://github.com/rob-slezak/TabFind/commit/9baea4078d5b343ed2718b1b776d901921dbd329

**Comment by ghost** [comment]
How exciting!  I clicked on the "Count Duplicate Tabs" settings but it shows 0 while the duplicate tabs shows 4 (bug).  Ideally, you want to hide the badge when it's 0 (hey hey hey.... I have nothing to say).

**Comment by rob-slezak** [comment]
Fixed the issue causing the badge to count duplicate tabs incorrectly, it should now match the duplicate view. https://github.com/rob-slezak/TabFind/commit/a67634a35fb0c65cfe1a491cc06ff85d9fc32e1e

Also, added hiding of the badge number when 0. https://github.com/rob-slezak/TabFind/commit/71c9c4f626a802105857f298f1fc28650a23fe6c

**Comment by ghost** [comment]
If I have two identical tabs is that 1 or 2 duplicates?  Semantically, I am thinking the first one is the original and the 2nd is the duplicate i.e. sum(count per group - 1).  The current counting is odd:

1. duplicate url1 (total 2); badge remains 0 as it's the current tab
2. move to different tab, badge goes from 0 to 2
3. duplicate url1 (3 in group), badge remains 2 irregardless of what tab is active
4. duplicate url2 (2 in group) badge is now 3
5. duplicate url2 (3 in group, badge is now 5

One minor unrelated issue, the window count is truncated but the "Al" button has a lot of padding.  Happy to file another issue if you prefer.
